baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en
name: 'Commerce Migrations'
primary: true
siteGroup: 378d9a00-6d65-4e45-b314-92db8a970c0e # Commerce Migrations
sortOrder: 1
